#!/usr/bin/env python3

import RPi.GPIO as GPIO
import time

START_BUTTON_PIN = 21

GPIO.setmode(GPIO.BCM)
GPIO.setup(START_BUTTON_PIN, GPIO.IN)

previous_state = 0 # stop the main code from being called twice in one toggle

while True:
	status = GPIO.input(START_BUTTON_PIN)
	if status == 0:
		previous_state = 0
		# do nothing

	if status == 1 and previous_state == 0:
		previous_state = 1
		print("STARTED")
		# run main.py

	time.sleep(0.1)

GPIO.cleanup()
